- Designed and deployed the mechanical all parts of the robotic arm using the "SolidWorks" tool caring for the mechanical criteria.
- Designed and developed the electronic circuits on the "Proteus" tool such as the control circuit and motor circuits.
- Designed, Implemented, and tested firmware for the ARM Robot and I used “PIC18Fxx microcontroller” as the main controller for controlling motors, capturing sensors, and store these reading to be read by a personal computer.
- Personal computer takes the sensors readings and gives motors angles to the main controller using the “Bluetooth” interface using the "Matlab" tool.
- Cared about issues like cost, other Embedded criteria, and Mechanical criteria.
